### ISSUE TITLE
How to use it with expo in this project?

### ISSUE THREAD

**Issue by abhidevsgit** [Gerlison/rn_boilerplate#4]

**Comment by Gerlison** [comment]
This template is based on CLI projects. Unfortunately you cant initialize an Expo Project with it.
But if you want to use the same folder structure, you can:
* Clone the repository
* Copy `src/` folder
* Paste on root of your project

This template contains `android/` and `ios/` folders in addition to third party libraries that may not work on Expo. Soon as possible I'll be working on a Expo version of this.
